#!/usr/bin/env bash
#
# Summary: Command line interface for Zas
#
# Usage: zas <command> [<args>]

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

export ZAS_ROOT="$bin_path/../"

command="$1"
case "$command" in
"")
  zas-help
  ;;
* )
  command_path="$(command -v "zas-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "zas: no such command '$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
