#!/usr/bin/env bash
#
# Summary: List all available commands with a prefix
# Usage: zas _commands <prefix>
#
# Looks for executable files prefixed with prefix- and
# displays each suffix as an available command.

set -e

if [ "$#" -ne 1 ]; then
  zas-help _commands
  exit 1
fi

prefix="$1"

IFS=: paths=($PATH)

shopt -s nullglob

{ for path in "${paths[@]}"; do
    for command in "${path}/$prefix-"*; do
      command="${command##*$prefix-}"
      if [[ ! "$command" == _* ]]; then
        echo ${command}
      fi
    done
  done
} | sort | uniq
