#!/usr/bin/env bash

set -e

name="$(pwd)"
name="${name##*/}"

if [ -e "$HOME/.zas/apps/${name}" ]; then
  curl -H "Host: zas.dev" "localhost/apps/${name}/term"
else
  echo "zas: app with name '${name}' not configured"
  exit 1
fi
