#!/usr/bin/env bash
#
# Summary: Lists configured applications
#
# Usage: zas list
#
# Lists configured applications.

set -e

for file in ~/.zas/apps/*; do
  echo "${file##*/} -> $(readlink $file)"
done
