#!/usr/bin/env bash
#
# Summary: Remove an application
#
# Usage: zas unlink
#
# Removes an application.
#
# The name of the current directory will be used as the application name.

set -e

name="$(pwd)"
name="${name##*/}"

if [ -e "$HOME/.zas/apps/${name}" ]; then
  rm "$HOME/.zas/apps/${name}"
else
  echo "zas: app with name '${name}' not configured"
  exit 1
fi
