#!/usr/bin/env bash

set -e

name="$(pwd)"
name="${name##*/}"

if [ -e "$HOME/.zas/apps/${name}" ]; then
  tail -f "$HOME/.zas/logs/${name}"
else
  echo "zas: app with name '${name}' not configured"
  exit 1
fi
