#!/usr/bin/env bash
#
# Summary: Configure an application with zas
#
# Usage: zas link
#
# Configures an application with zas.
#
# The name of the current directory will be used as the application name.

set -e

name="$(pwd)"
name="${name##*/}"

if [ -e "$HOME/.zas/apps/${name}" ]; then
  echo "zas: app with name '${name}' already configured"
  exit 1
else
  ln -s "$(pwd)" "$HOME/.zas/apps/${name}"
fi
