#!/usr/bin/env bash
#
# Summary: Setup zas system hooks
#
# Usage: zas install

set -e

FIREWALL_PLIST_PATH="/Library/LaunchDaemons/com.zas.firewall.plist"

# Create required directories

mkdir -p "$HOME/.zas/apps"
mkdir -p "$HOME/.zas/logs"

# Install DNS resolver

echo "Installing DNS resolver"
sudo mkdir -p /etc/resolver/
sudo cp -f "$ZAS_ROOT/resources/dev-resolver" /etc/resolver/dev

# Install port forwarding

echo "Installing port forward"
sudo cp "$ZAS_ROOT/resources/com.zas.firewall.plist" "${FIREWALL_PLIST_PATH}"

sudo launchctl bootstrap system "${FIREWALL_PLIST_PATH}" 2>/dev/null
sudo launchctl enable system/com.zas.firewall 2>/dev/null
sudo launchctl kickstart -k system/com.zas.firewall 2>/dev/null
