#!/usr/bin/env bash

# If for some reason only part of the script gets downloaded, this will prevent any of it from being executed

    {

# Stop script if any command returns non zero exit code

    set -e

# Set up environment

    ZAS_ROOT="$HOME/Library/Application Support/Zas"

    ZASD_PLIST_PATH="$HOME/Library/LaunchAgents/com.zas.zasd.plist"
    FIREWALL_PLIST_PATH="/Library/LaunchDaemons/com.zas.firewall.plist"

# Fail fast if Zas is not installed

    if [ ! -d "$ZAS_ROOT" ]; then
      echo "error: zas is not installed"
      exit 1
    fi

# Remove root directory

    echo "Removing Zas"
    rm -rf "$ZAS_ROOT"

# Stop and remove the Zas daemon

    echo "Stopping the Zas Daemon"
    launchctl unload "$ZASD_PLIST_PATH" 2>/dev/null || true
    rm -f "$ZASD_PLIST_PATH"

# Uninstall the DNS resolver

    echo "Uninstalling DNS resolver"
    grep -Rl 'Generated by Zas' /etc/resolver/ | sudo xargs rm

# Uninstall port forwarding

    echo "Uninstalling port forward"
    sudo launchctl unload "$FIREWALL_PLIST_PATH" 2>/dev/null || true
    sudo rm -f "$FIREWALL_PLIST_PATH"

# Make sure the user knows it was completed successfully

    echo "Done"

    }
