#!/usr/bin/env bash

set -e

ZAS_ROOT="$HOME/Library/Application Support/Zas"

ZASD_PLIST_PATH="$HOME/Library/LaunchAgents/com.zas.zasd.plist"
FIREWALL_PLIST_PATH="/Library/LaunchDaemons/com.zas.firewall.plist"

if [ ! -d "$ZAS_ROOT" ]; then
  echo "error: zas is not installed"
  exit 1
fi

echo "Removing Zas"
rm -rf "$ZAS_ROOT"

echo "Stopping the Zas Daemon"
launchctl unload "$ZASD_PLIST_PATH" 2>/dev/null || true
rm -f "$ZASD_PLIST_PATH"

echo "Uninstalling DNS resolver"
grep -Rl 'Generated by Zas' /etc/resolver/ | sudo xargs rm

echo "Uninstalling port forward"
sudo launchctl unload "$FIREWALL_PLIST_PATH" 2>/dev/null || true
sudo rm -f "$FIREWALL_PLIST_PATH"

echo "Done"
